version: '3.9'
services:
  mysql:
    image: mysql:8.4
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ticketdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  backend:
    build:
      context: ./ticket-booking-backend
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/ticketdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - DB_USERNAME=root
      - DB_PASSWORD=password
      - RAZORPAY_ENABLED=false
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE=http://backend:8080
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  mysql_data: